services:
  db:
    image: mysql:8.0.32
    container_name: security_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: secursys
      MYSQL_USER: lazz
      MYSQL_PASSWORD: ultrauser
    ports:
      - 3306:3306
  mongo:
    image: mongo:latest
    container_name: security_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: secursys


